function B_em = B_iz(I, z, struct_params)
%B_IZ
%    B_EM = B_IZ(I,L,MU_IRON,N,R,Z)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-May-2021 22:21:28

mu_core = struct_params.mu_core;    % Permeability of electromagnet core
n = struct_params.n;                % Number of electromagnet coil turns (#)
r = struct_params.r;                % Radius of electromagnet coil (m)
l = struct_params.l;                % Length of electromagnet coil (m)

t2 = l+z;
t3 = r.^2;
B_em = (I.*mu_core.*n.*(t2.*1.0./sqrt(t3+t2.^2)-z.*1.0./sqrt(t3+z.^2)))./(l.*2.0);
