function B_em = B_iz(I, z, struct_params)

k = struct_params.k; % Magnetic field scaling constant
l = struct_params.l; % Length of the electromagnet
r = struct_params.r; % Radius of the electromagnet


%B_IZ
%    B_EM = B_IZ(I,K,L,R,Z)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    06-May-2021 18:17:16

t2 = l+z;
t3 = r.^2;
B_em = (I.*k.*(t2.*1.0./sqrt(t3+t2.^2)-z.*1.0./sqrt(t3+z.^2)))./(l.*2.0);
