function force = F_iz(I, z, struct_params)
%F_IZ
%    FORCE = F_IZ(I,L,L_MAG,MU_IRON,N,P,R,Z)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-May-2021 22:19:31

mu_core = struct_params.mu_core;    % Permeability of electromagnet core
n = struct_params.n;                % Number of turns in electromagnet coil (#)
l = 0.08;                           % Length of electromagnet
r = struct_params.r;                % Radius of electromagnet coil
p = struct_params.p;                % Pole strength of permanent magnet (amp-meters)
l_mag = 0.01;                       % Length of permanent magnet (m)

t2 = l+z;
t3 = r.^2;
t4 = z.^2;
t5 = t2.^2;
t6 = t3+t4;
t7 = t3+t5;
force = (I.*l_mag.*mu_core.*n.*p.*(t4.*1.0./t6.^(3.0./2.0)-t5.*1.0./t7.^(3.0./2.0)-1.0./sqrt(t6)+1.0./sqrt(t7)))./(l.*2.0);
